# Generated by Django 2.2.19 on 2022-11-30 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(max_length=500, verbose_name='Descrição')),
                ('carga_horaria', models.IntegerField(verbose_name='Carga Horária')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Faixa Salarial')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('data_nascimento', models.DateField(blank=True, help_text='Por favor use o seguinte formato: <em>DD/MM/YYYY', null=True, verbose_name='Data de Nascimento')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='E-mail')),
                ('logradouro', models.CharField(max_length=100, verbose_name='Logradouro')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro')),
                ('numero', models.IntegerField(blank=True, verbose_name='Número')),
                ('complemento', models.IntegerField(null=True, verbose_name='Complemento')),
                ('cep', models.CharField(help_text='Format: XXXXX-XXX', max_length=8, verbose_name='CEP')),
                ('cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.Cargo')),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
            },
        ),
    ]
