# Generated by Django 2.2.19 on 2022-11-30 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0003_auto_20221130_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='opcao',
            field=models.CharField(blank=True, choices=[('F', 'Feminino'), ('M', 'Masculino'), ('N', 'Nenhuma das opções')], max_length=1, verbose_name='Sexo'),
        ),
    ]
