# Generated by Django 2.2.19 on 2022-11-30 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0004_funcionario_opcao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=200, null=True, verbose_name='E-mail')),
                ('contato', models.CharField(blank=True, max_length=14, null=True, verbose_name='Número de contato')),
                ('logradouro', models.CharField(max_length=100, null=True, verbose_name='Logradouro')),
                ('bairro', models.CharField(max_length=100, null=True, verbose_name='Bairro')),
                ('numero', models.IntegerField(null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=30, null=True, verbose_name='Complemento')),
                ('cep', models.CharField(help_text='Format: XXXXX-XXX', max_length=9, null=True, verbose_name='CEP')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('ie', models.CharField(max_length=13, null=True, verbose_name='Inscrição Estadual')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.Empresa'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aplic.Empresa'),
        ),
    ]
