# Generated by Django 2.2.19 on 2022-11-30 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplic', '0005_auto_20221130_0050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='empresa',
        ),
        migrations.CreateModel(
            name='Ponto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_created=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('observacao', models.TextField(blank=True, max_length=300, null=True, verbose_name='Observações')),
                ('funcionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplic.Funcionario')),
            ],
            options={
                'verbose_name': 'Ponto',
                'verbose_name_plural': 'Pontos',
            },
        ),
    ]
